In [48]:
import numpy as np
from numpy import genfromtxt
#genfromtxt generates an array from a text file

In [49]:
data= genfromtxt('DATA/bank_note_data.txt',delimiter=',')

In [50]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [51]:
label= data[:,4]
label

array([0., 0., 0., ..., 1., 1., 1.])

In [52]:
features=data[:,0:4]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [53]:
X=features
y=label

In [54]:
from sklearn.model_selection import train_test_split


In [55]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [56]:
from sklearn.preprocessing import MinMaxScaler
scaler_object=MinMaxScaler()
#for scaling everything in the range 1-0

In [57]:
scaler_object.fit(X_train)
#fit only the training data data and never the test data
#test data should never be shown to any model

MinMaxScaler(copy=True, feature_range=(0, 1))

In [58]:
scaled_X_train=scaler_object.transform(X_train)
scaled_X_test=scaler_object.transform(X_test)

In [59]:
scaled_X_train.max()

1.0000000000000002

In [60]:
scaled_X_train.min()

0.0

In [61]:
scaled_X_train
#everything is between 0 and 1

array([[4.44850688e-01, 5.14130449e-01, 2.18194638e-01, 8.50172258e-01],
       [6.53339968e-01, 5.82655745e-01, 9.93242398e-02, 8.17696322e-01],
       [4.81846700e-01, 6.69377018e-01, 3.61193167e-01, 7.63368407e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

In [62]:
from keras.models import Sequential
from keras.layers import Dense

In [63]:
model=Sequential()
#creating the model

#4 input features, 4 ouptuts and using rectifier linier unit
model.add(Dense(4,input_dim=4,activation='relu'))

#hidden layer
model.add(Dense(8,activation='relu'))

#output layer, sigmoid function is used for the output to be as 0 or 1
model.add(Dense(1,activation='sigmoid'))

In [64]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
#using the crossentropy cost function

In [65]:
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
 - 1s - loss: 0.6858 - acc: 0.5517
Epoch 2/50
 - 0s - loss: 0.6724 - acc: 0.6975
Epoch 3/50
 - 0s - loss: 0.6538 - acc: 0.7291
Epoch 4/50
 - 0s - loss: 0.6296 - acc: 0.7486
Epoch 5/50
 - 0s - loss: 0.5981 - acc: 0.7671
Epoch 6/50
 - 0s - loss: 0.5630 - acc: 0.7726
Epoch 7/50
 - 0s - loss: 0.5351 - acc: 0.7791
Epoch 8/50
 - 0s - loss: 0.5117 - acc: 0.7943
Epoch 9/50
 - 0s - loss: 0.4912 - acc: 0.8052
Epoch 10/50
 - 0s - loss: 0.4715 - acc: 0.8150
Epoch 11/50
 - 0s - loss: 0.4542 - acc: 0.8172
Epoch 12/50
 - 0s - loss: 0.4380 - acc: 0.8215
Epoch 13/50
 - 0s - loss: 0.4230 - acc: 0.8357
Epoch 14/50
 - 0s - loss: 0.4085 - acc: 0.8531
Epoch 15/50
 - 0s - loss: 0.3952 - acc: 0.8716
Epoch 16/50
 - 0s - loss: 0.3824 - acc: 0.8705
Epoch 17/50
 - 0s - loss: 0.3703 - acc: 0.8803
Epoch 18/50
 - 0s - loss: 0.3585 - acc: 0.8868
Epoch 19/50
 - 0s - loss: 0.3479 - acc: 0.8901
Epoch 20/50
 - 0s - loss: 0.3373 - acc: 0.8934
Epoch 21/50
 - 0s - loss: 0.3282 - acc: 0.8966
Epoch 22/50
 - 0s - lo

In [66]:
from sklearn.metrics import classification_report,confusion_matrix

In [70]:
predictions= model.predict_classes(scaled_X_test)
confusion_matrix(y_test,predictions)

array([[252,   5],
       [ 18, 178]], dtype=int64)

In [72]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

         0.0       0.93      0.98      0.96       257
         1.0       0.97      0.91      0.94       196

   micro avg       0.95      0.95      0.95       453
   macro avg       0.95      0.94      0.95       453
weighted avg       0.95      0.95      0.95       453



In [73]:
model.save('firstmodel.h5')
#saving the model for resuing again

In [75]:
from keras.models import load_model
newmodel=load_model('firstmodel.h5')

In [78]:
prediction1=newmodel.predict_classes(scaled_X_test)
confusion_matrix(y_test,prediction1)

array([[252,   5],
       [ 18, 178]], dtype=int64)